#!/bin/sh
# Validate the distributable Design Arc plugin without caller-directory state.

set -eu

# Validation imports Python helpers and also scans the checkout for local paths.
# Keep generated bytecode out of the tree so callers need no environment override.
PYTHONDONTWRITEBYTECODE=1
export PYTHONDONTWRITEBYTECODE

script_dir=$(CDPATH= cd "$(dirname "$0")" && pwd)
repo_root=$(CDPATH= cd "$script_dir/.." && pwd)
plugin_path="$repo_root/plugins/design-arc"
skill_path="$plugin_path/skills/design-arc/SKILL.md"
metadata_path=${VALIDATE_OPENAI_YAML:-"$plugin_path/skills/design-arc/agents/openai.yaml"}
codex_skills_dir=${CODEX_SKILLS_DIR:-"$HOME/.codex/skills"}
plugin_validator="$codex_skills_dir/.system/plugin-creator/scripts/validate_plugin.py"
skill_validator="$codex_skills_dir/.system/skill-creator/scripts/quick_validate.py"

fail() {
  printf '%s\n' "FAIL: $*" >&2
  exit 1
}

require_file() {
  [ -f "$repo_root/$1" ] || fail "missing required file: $1"
}

for required_file in \
  README.md \
  LICENSE \
  .gitignore \
  examples/prompts.md \
  docs/codex-operating-layer.md \
  docs/advanced-controls.md \
  docs/trusted-sources/README.md \
  docs/trusted-sources/motion.md \
  docs/trusted-sources/platform-guidance.md \
  docs/trusted-sources/product-benchmarks.md \
  docs/trusted-sources/visualization.md \
  docs/validation/behavioral-validation.md \
  .claude-plugin/marketplace.json \
  .agents/plugins/marketplace.json \
  gemini-extension.json \
  skills/design-arc/SKILL.md \
  skills/design-arc/references/graph-record.schema.json \
  skills/design-arc/scripts/validate-graph-record.py \
  claude-plugins/design-arc/.claude-plugin/plugin.json \
  claude-plugins/design-arc/skills/design-arc/SKILL.md \
  claude-plugins/design-arc/skills/design-arc/references/graph-record.schema.json \
  claude-plugins/design-arc/skills/design-arc/scripts/validate-graph-record.py \
  plugins/design-arc/.codex-plugin/plugin.json \
  plugins/design-arc/skills/design-arc/SKILL.md \
  plugins/design-arc/skills/design-arc/agents/openai.yaml \
  plugins/design-arc/skills/design-arc/references/graph-record.schema.json \
  plugins/design-arc/skills/design-arc/scripts/validate-graph-record.py \
  scripts/check-workflow-contracts.py \
  scripts/check-claude-state-contracts.py \
  scripts/check-antigravity-runtime-contracts.py \
  scripts/compose-design-arc-skills.py \
  scripts/test-design-arc-docs.sh \
  scripts/test-design-arc-identity.sh \
  scripts/test-plugin-install.sh \
  scripts/test-plugin-migration.sh \
  scripts/test-plugin-upgrade-state.py \
  scripts/test-plugin-upgrade.sh \
  scripts/test-runtime-visualization-contracts.py \
  scripts/test-test-validate.sh \
  scripts/test-validate.sh \
  scripts/test-graph-records.py \
  scripts/test-claude-state-contracts.py \
  scripts/test-antigravity-runtime-contracts.py \
  scripts/test-claude-plugin-install.sh \
  scripts/test-claude-package.py \
  scripts/test-antigravity-package.py \
  scripts/test-skill-composition.py \
  scripts/validate-graph-record.py \
  scripts/test-workflow-contracts.py \
  scripts/validate.sh \
  shared/design-arc/VERSION \
  shared/design-arc/methodology.md \
  shared/design-arc/overlays/codex.md \
  shared/design-arc/overlays/claude.md
do
  require_file "$required_file"
done
printf '%s\n' 'PASS: required Design Arc files'

[ ! -d "$repo_root/plugins/fb-ux" ] || fail 'legacy fb-ux package remains active'
[ ! -d "$repo_root/plugins/apple-guidelines-stitch" ] || fail 'legacy apple-guidelines-stitch package remains active'

awk '
  NR == 1 { valid = ($0 == "---"); next }
  valid && $0 == "name: design-arc" { named = 1 }
  valid && $0 == "---" { closed = 1; exit }
  END { exit !(valid && closed && named) }
' "$skill_path" || fail 'Design Arc SKILL.md must begin with YAML frontmatter containing the exact internal name'
grep -F 'display_name: "Design Arc"' "$metadata_path" >/dev/null || fail 'Design Arc agent metadata must use the canonical display name'
printf '%s\n' 'PASS: Design Arc package metadata'

[ -f "$plugin_validator" ] || fail 'plugin validator is unavailable'
[ -f "$skill_validator" ] || fail 'skill validator is unavailable'
python3 -u "$plugin_validator" "$plugin_path"
python3 -u "$skill_validator" "$(dirname "$skill_path")"
printf '%s\n' 'PASS: plugin and embedded skill validation for Design Arc'

sh "$repo_root/scripts/test-design-arc-identity.sh"
sh "$repo_root/scripts/test-design-arc-docs.sh"
python3 "$repo_root/scripts/check-workflow-contracts.py"
python3 "$repo_root/scripts/check-claude-state-contracts.py"
python3 "$repo_root/scripts/check-antigravity-runtime-contracts.py"
python3 "$repo_root/scripts/test-workflow-contracts.py"
python3 "$repo_root/scripts/test-runtime-visualization-contracts.py"
python3 "$repo_root/scripts/test-claude-state-contracts.py"
python3 "$repo_root/scripts/test-antigravity-runtime-contracts.py"
python3 "$repo_root/scripts/compose-design-arc-skills.py" --platform codex --check
python3 "$repo_root/scripts/compose-design-arc-skills.py" --platform claude --check
python3 "$repo_root/scripts/compose-design-arc-skills.py" --platform antigravity --check
python3 "$repo_root/scripts/test-skill-composition.py"
python3 "$repo_root/scripts/test-claude-package.py"
python3 "$repo_root/scripts/test-antigravity-package.py"
if python3 "$repo_root/scripts/test-graph-records.py"
then
  :
else
  fail 'graph-record test failed'
fi
printf '%s\n' 'PASS: focused identity, documentation, and workflow contracts'

private_key_prefix='-----BEGIN '
private_key_marker='PRIVATE KEY'
private_key_suffix='-----'
private_key_pattern="${private_key_prefix}[A-Z ]*${private_key_marker}[ A-Z-]*${private_key_suffix}"
credential_pattern='^[[:space:]]*((export|env)[[:space:]]+)*([A-Z0-9]+[_-])?(API[_-]?KEY|ACCESS[_-]?KEY([_-]?ID)?|AUTH[_-]?TOKEN|CLIENT[_-]?SECRET|GITHUB[_-]?TOKEN|OPENAI[_-]?API[_-]?KEY|AWS[_-]?ACCESS[_-]?KEY([_-]?ID)?|PASSWORD|PRIVATE[_-]?KEY|SECRET|TOKEN)[[:space:]]*[:=][[:space:]]*[^[:space:]#]'
quoted_credential_pattern="^[[:space:]]*[{]?[[:space:]]*['\"]([A-Z0-9]+[_-])?(API[_-]?KEY|ACCESS[_-]?KEY([_-]?ID)?|AUTH[_-]?TOKEN|CLIENT[_-]?SECRET|GITHUB[_-]?TOKEN|OPENAI[_-]?API[_-]?KEY|AWS[_-]?ACCESS[_-]?KEY([_-]?ID)?|PASSWORD|PRIVATE[_-]?KEY|SECRET|TOKEN)['\"][[:space:]]*:[[:space:]]*['\"]?[^[:space:]#,'\"}]+"

contains_private_material() {
  scan_root=$1
  find "$scan_root" \
    \( -path "$scan_root/.git" -o -path "$scan_root/.worktrees" -o -path "$scan_root/.superpowers" \) -prune -o \
    -type f \
    ! -name '*.pyc' \
    ! -name '*.pyo' \
    -exec grep -i -E -e "$private_key_pattern" -e "$credential_pattern" -e "$quoted_credential_pattern" {} \; | grep . >/dev/null
}

if contains_private_material "$repo_root"
then
  fail 'private key or credential assignment found'
fi

if [ -n "${VALIDATE_EXTRA_SCAN_ROOT:-}" ]
then
  [ -d "$VALIDATE_EXTRA_SCAN_ROOT" ] || fail 'VALIDATE_EXTRA_SCAN_ROOT must name a directory'
  if contains_private_material "$VALIDATE_EXTRA_SCAN_ROOT"
  then
    fail 'private key or credential assignment found'
  fi
fi

user_path_prefix='/''Users/'
if find "$repo_root" \
  \( -path "$repo_root/.git" -o -path "$repo_root/.worktrees" -o -path "$repo_root/.superpowers" \) -prune -o \
  -type f \
  ! -name '*.pyc' \
  ! -name '*.pyo' \
  ! -path "$repo_root/docs/superpowers/plans/*" \
  ! -path "$repo_root/docs/superpowers/specs/*" \
  -exec grep -l -F "$user_path_prefix" {} \; | grep . >/dev/null
then
  fail "local ${user_path_prefix} path found outside historical design/plan docs"
fi

artifact_pattern='\.(png|jpe?g|gif|webp|avif|heic|svg|psd|psb|ai|sketch|fig|xd|afdesign|afphoto|indd|eps|tiff?|bmp|raw|dng|cr2|nef|mp4|mov|m4v|avi|webm|mkv|wmv|flv|mp3|wav|aac|m4a|flac|ogg|aiff)$'
if find "$repo_root" \
  \( -path "$repo_root/.git" -o -path "$repo_root/.worktrees" -o -path "$repo_root/.superpowers" \) -prune -o \
  -type f \
  ! -name '*.pyc' \
  ! -name '*.pyo' \
  -print | grep -i -E "$artifact_pattern" >/dev/null
then
  fail 'proprietary image or media artifact found'
fi
printf '%s\n' 'PASS: credential, local-path, and media safety scans'

sh -n \
  "$repo_root/scripts/test-design-arc-docs.sh" \
  "$repo_root/scripts/test-design-arc-identity.sh" \
  "$repo_root/scripts/test-plugin-install.sh" \
  "$repo_root/scripts/test-plugin-migration.sh" \
  "$repo_root/scripts/test-plugin-upgrade.sh" \
  "$repo_root/scripts/test-claude-plugin-install.sh" \
  "$repo_root/scripts/test-test-validate.sh" \
  "$repo_root/scripts/test-validate.sh" \
  "$repo_root/scripts/validate.sh"
python3 - \
  "$repo_root/scripts/check-workflow-contracts.py" \
  "$repo_root/scripts/check-claude-state-contracts.py" \
  "$repo_root/scripts/check-antigravity-runtime-contracts.py" \
  "$repo_root/scripts/compose-design-arc-skills.py" \
  "$repo_root/scripts/test-graph-records.py" \
  "$repo_root/scripts/test-claude-package.py" \
  "$repo_root/scripts/test-antigravity-package.py" \
  "$repo_root/scripts/test-plugin-upgrade-state.py" \
  "$repo_root/claude-plugins/design-arc/skills/design-arc/scripts/validate-graph-record.py" \
  "$repo_root/plugins/design-arc/skills/design-arc/scripts/validate-graph-record.py" \
  "$repo_root/scripts/validate-graph-record.py" \
  "$repo_root/scripts/test-workflow-contracts.py" \
  "$repo_root/scripts/test-claude-state-contracts.py" \
  "$repo_root/scripts/test-antigravity-runtime-contracts.py" \
  "$repo_root/scripts/test-runtime-visualization-contracts.py" \
  "$repo_root/scripts/test-skill-composition.py" <<'PY'
from pathlib import Path
import sys

for name in sys.argv[1:]:
    path = Path(name)
    compile(path.read_text(encoding="utf-8"), str(path), "exec")
PY
printf '%s\n' 'PASS: shell and Python syntax checks'

if sh "$repo_root/scripts/test-plugin-install.sh"
then
  :
else
  fail 'isolated plugin installation smoke failed'
fi

if sh "$repo_root/scripts/test-claude-plugin-install.sh"
then
  :
else
  fail 'isolated Claude Code plugin installation and load smoke failed'
fi

if sh "$repo_root/scripts/test-plugin-migration.sh"
then
  :
else
  fail 'isolated plugin migration smoke failed'
fi

if DESIGN_ARC_UPGRADE_TARGET_VERSION=9.9.9 sh "$repo_root/scripts/test-plugin-upgrade.sh" >/dev/null 2>&1
then
  fail 'upgrade harness accepted a target version that disagrees with the manifest'
else
  printf '%s\n' 'PASS: upgrade harness rejects a target-version mismatch'
fi

if sh "$repo_root/scripts/test-plugin-upgrade.sh"
then
  :
else
  fail 'isolated plugin upgrade smoke failed'
fi

if DESIGN_ARC_UPGRADE_BASELINE_SHA=489988474dce4a4b0da7a5c48104e9d548c107bd \
  DESIGN_ARC_UPGRADE_BASELINE_VERSION=0.2.3 \
  DESIGN_ARC_TEST_DOWNGRADE=1 \
  sh "$repo_root/scripts/test-plugin-upgrade.sh"
then
  :
else
  fail 'isolated exact-candidate upgrade and downgrade smoke failed'
fi

if DESIGN_ARC_UPGRADE_BASELINE_SHA=55b03baf4a8dc0b52f0702f1236a865ac2c797b6 \
  DESIGN_ARC_UPGRADE_BASELINE_VERSION=0.3.0 \
  sh "$repo_root/scripts/test-plugin-upgrade.sh"
then
  :
else
  fail 'isolated public 0.3.0 to 0.5.0 upgrade smoke failed'
fi

if DESIGN_ARC_UPGRADE_BASELINE_SHA=bd5443df13bab19ba066be8014ff2e1ae87cc9f6 \
  DESIGN_ARC_UPGRADE_BASELINE_VERSION=0.3.1 \
  sh "$repo_root/scripts/test-plugin-upgrade.sh"
then
  :
else
  fail 'isolated public 0.3.1 to 0.5.0 upgrade smoke failed'
fi

if git -C "$repo_root" rev-parse --is-inside-work-tree >/dev/null 2>&1
then
  git -C "$repo_root" diff --check
  printf '%s\n' 'PASS: git diff check'
else
  printf '%s\n' 'PASS: git diff check skipped (not a worktree)'
fi

printf '%s\n' 'PASS: Design Arc repository validation'
